Azure/custom-script-extension-linux

blobutil/url.go
blobutil/url_test.go

blobutil: parse blob info from url

---

download/blob.go
download/blob_test.go
download/downloader.go
download/downloader_test.go
download/url.go
download/url_test.go

This one is fairly simple:
```
package download
FUNCTIONS
func Download(d Downloader) (io.ReadCloser, error)
Download retrieves a response body and checks the response status code
to see if it is 200 OK and then returns the response body. It issues a
new request every time called. It is caller's responsibility to close
the response body.
TYPES
type Downloader interface {
// GetRequest returns a new GET request for the resource.
GetRequest() (*http.Request, error)
}
Downloader describes a method to download files.
func NewBlobDownload(accountName, accountKey string, blob blobutil.AzureBlobRef) Downloader
NewBlobDownload creates a new Downloader for a blob hosted in Azure Blob
Storage.
func NewURLDownload(url string) Downloader
NewURLDownload creates a new downloader with the provided URL …
```

download: utils to download files and blobs

---

exec.go
exec_test.go

ExecCmdInDir executes the given command in given directory and saves output to ./stdout and ./stderr files (truncates files if exists, creates them if not with 0600/-rw------- permissions).
Ideally, we execute commands only once per sequence number in custom-script-extension, and save their output under `/var/lib/waagent/<dir>/download/<seqnum>/*`.

exec: helper method to run cmds and save outputs

---

files.go
files_test.go

These methods will help download a file from URL,
save it to a directory with proper name and apply
post-download/pre-execution processing (DOS, BOM etc)
on it.

Process file urls

---

download/save_test.go

nit: better errors for chmod comparisons in tests

---

files_test.go

it's a bit hard to test error cases in here (as it'll trigger 2 minute retries etc)

files_test.go: increase coverage

---

.gitignore
cmds.go
main.go

Some skeleton code for starting to write main executable.

main.go: starting to write main.go

---

.gitignore

This way we only ignore "bin" at the root level and not in
nested directories. I'll be adding a Makefile to utilize these dirs.
Signed-off-by: Ahmet Alp Balkan <ahmetalpbalkan@gmail.com>

.gitignore minor update

---

seqnum/seqnum.go
seqnum/seqnum_test.go

Changing the seqnum helper method again to give the following truth table:
(stored,given) => outcome
(none, 0) => true
(0, 0) => false
(0, 1) => true
(1, 0) => false
(1, 1) => false
(1, 2) => true

seqnum: convert <= logic to <

---

Godeps/Godeps.json
vendor/github.com/Azure/azure-docker-extension/pkg/vmextension/status/status.go

Addresses status file write atomicity issue.
Closes #37.

Vendor pkg/vmextension/status again

---

Godeps/Godeps.json
vendor/github.com/Azure/azure-docker-extension/LICENSE
vendor/github.com/Azure/azure-docker-extension/pkg/vmextension/handlerenv.go

trivial fix, will directly merge...

Vendor azure-docker-extension to latest

---

Godeps/Godeps.json
integration-test/test/handler-commands.bats
vendor/github.com/Azure/azure-sdk-for-go/storage/blob.go
vendor/github.com/Azure/azure-sdk-for-go/storage/client.go
vendor/github.com/Azure/azure-sdk-for-go/storage/file.go

- Vendor azure-sdk-for-go latest.
- contains a fix with handling of special characters in blob/container names
- integration-test: update test to cover blob name with spaces
cc: @boumenot

Vendor azuresdk

---

integration-test/test/handler-commands.bats
main/main.go

report stdout/stderr on failure

---

integration-test/test/handler-commands.bats
main/cmds.go
main/main.go

extended exit codes

---

README.md
integration-test/test/handler-commands.bats
main/cmds.go
main/cmds_test.go
main/files.go
main/files_test.go
main/handlersettings.go
main/handlersettings_test.go
main/schema.go
main/schema_test.go
main/telemetry.go
main/telemetry_test.go
misc/manifest.xml
vendor/github.com/ahmetalpbalkan/go-httpbin/handlers.go

* report stdout/stderr on failure
* support fileUris in protected settings
* telemetry
* allow user to turn of dos2unix conversion
* better exit codes to track failure cases

support script command

---

main/cmds.go
misc/manifest.xml

Removing stdout/stderr from telemetry

Removing stdout/stderr from telemetry

---

misc/manifest.xml
pkg/download/downloader.go
pkg/download/downloader_test.go
pkg/download/retry_test.go

Updated error message when download using MSI fails

Updated error message when download using MSI fails

---

README.md

Updated doc for MSI property to mention that it must be specified in protected settings only.

Updated doc for MSI property

---

pkg/download/blobwithmsitoken.go
pkg/download/blobwithmsitoken_test.go

Mirroring functionality in CSE Windows

[Don't Merge] Making Azure blob validaiton more generic to support NCs

---

.config/CredScanSuppressions.json
.gitignore

Added suppression rules for credscan for fake service account keys for schema testing.

Suppress credscan for fake service account keys for schema testing

---

main/cmds.go
main/cmds_test.go

PR 200 doesn't address the issue directly and introduces a new bug, will revert to unblock current release.

Reverting PR 200 -- seqNum fix 

---

misc/manifest.xml

Changes include: 
[pr 214](https://github.com/Azure/custom-script-extension-linux/pull/214)

Increment CSE Linux Version to 2.1.9

---

misc/manifest.xml

Changes: 
https://github.com/Azure/custom-script-extension-linux/pull/216

CSE 2.1.10 Update

---

misc/manifest.xml

Increments CSE Linux version to 2.1.11

Increments extension version

---

misc/manifest.xml

Upversion CSE linux for publishing signature.

Upversion CSE linux
