schema.go
schema_test.go

These utility functions use json-schema (https://tools.ietf.org/html/draft-zyp-json-schema-04)
to validate and if necessary, error out when users specify extra
fields, wrong types, omit required fields etc.
This will save us many validation checks in the code, such as if the required fields are there,
if the inputs match the required format and so on.

json-schema checking for handler settings

---

Godeps/Godeps.json
cmd.go
cmd_test.go
vendor/github.com/google/shlex/COPYING
vendor/github.com/google/shlex/README
vendor/github.com/google/shlex/shlex.go

There's this https://github.com/flynn-archive/go-shlex/ package that is a fork of Google's go-shlex that got deprecated. (Apache 2.0 LICENSE).
Added a wrapper function for that and tests around it. Also vending the source code for that.

parseCmd: shlex functionality

---

download/downloader_test.go
download/retry.go
download/retry_test.go

WithRetries will retry any download failure and will sleep
in exponentially increasing durations up to 5 min. (5s, 10s,
20s, 40s, 80s, 160s)
The existing extension sleeps a fixed amount and up to 10 minutes.
It also retries all errors (bad host, 404s etc). I kept that part
the same, can be improved with an IsRetryable func later on perhaps.

download: add WithRetries method

---

download/retry.go
download/retry_test.go

the old agent retries constant time for 10*20s=200s. modifying
this to retry for total 189s. to be closer to 3 minutes instead
of minutes.

download/retry: reduce retry duration

---

seqnum/seqnum.go
seqnum/seqnum_test.go

I gave a thought about using/extending docker-extension's
seqnumfile pkg but it has some hardcoded stuff and designed to
prevent executing the sequence number simultaneously.
This code is shorter and exposes only methods to make sure
we only process sequence numbers greater than the stored one.

seqnum: sequence number tracking via file

---

Godeps/Godeps.json
vendor/github.com/go-kit/kit/LICENSE
vendor/github.com/go-kit/kit/log/README.md
vendor/github.com/go-kit/kit/log/doc.go
vendor/github.com/go-kit/kit/log/json_logger.go
vendor/github.com/go-kit/kit/log/log.go
vendor/github.com/go-kit/kit/log/logfmt_logger.go
vendor/github.com/go-kit/kit/log/nop_logger.go
vendor/github.com/go-kit/kit/log/stdlib.go
vendor/github.com/go-kit/kit/log/sync.go
vendor/github.com/go-kit/kit/log/value.go
vendor/github.com/go-logfmt/logfmt/.gitignore
vendor/github.com/go-logfmt/logfmt/.travis.yml
vendor/github.com/go-logfmt/logfmt/LICENSE
vendor/github.com/go-logfmt/logfmt/README.md
vendor/github.com/go-logfmt/logfmt/decode.go
vendor/github.com/go-logfmt/logfmt/doc.go
vendor/github.com/go-logfmt/logfmt/encode.go
vendor/github.com/go-logfmt/logfmt/fuzz.go
vendor/github.com/go-logfmt/logfmt/jsonstring.go
vendor/github.com/go-stack/stack/.travis.yml
vendor/github.com/go-stack/stack/LICENSE.md
vendor/github.com/go-stack/stack/README.md
vendor/github.com/go-stack/stack/stack.go
vendor/github.com/kr/logfmt/.gitignore
vendor/github.com/kr/logfmt/Readme
vendor/github.com/kr/logfmt/decode.go
vendor/github.com/kr/logfmt/scanner.go
vendor/github.com/kr/logfmt/unquote.go

Vendoring-only change. Adding [go-kit logger](https://godoc.org/github.com/go-kit/kit/log) library.
Example logs output from the main process will look like:
```
time=2016-07-22T06:07:34Z operation=Install seq=0 event=++start
time=2016-07-22T06:07:34Z operation=Install seq=0 event="created data dir" path=/var/lib/azure/custom-script
time=2016-07-22T06:07:34Z operation=Install seq=0 event=installed
time=2016-07-22T06:07:34Z operation=Install seq=0 event=--end
time=2016-07-22T06:07:35Z operation=Enable seq=0 event=++start
time=2016-07-22T06:07:35Z operation=Enable seq=0 event="parsed settings"
time=2016-07-22T06:07:35Z operation=Enable seq=0 event="comparing seqnum"
time=2016-07-22T06:07:35Z operation=Enable seq=0 event="seqnum saved" path=/var/lib/azure/custom-script/seqnum …
```

Vendor logging dependencies

---

seqnum/seqnum.go
seqnum/seqnum_test.go

This package was designed to be used to make sure we do not
execute same or lower sequence numbers more than once. Changing
the method accordingly to be more useful in that regard.
Signed-off-by: Ahmet Alp Balkan

seqnum: update IsSmallerThan→IsSmallerOrEqualThan

---

integration-test/test/basic.bats
integration-test/test/handler-commands.bats
integration-test/test/test_helper.bash

The integration tests use `bats` to run the scenarios as bash scripts.
To test the extension handler functionality, we simply:
- build a Docker image using test.Dockerfile
- copy some files from ` make it look like a `/var/lib/waagent` directory
- copy extension binary into the container
- remove the `test` container if it exists
- create a Docker container (name: `test`) from image
- specify which handler subcommand will be invoked (e.g. `fake-waagent
install`)
- push .settings file and certificate/private key to the container (.crt, .prv)
- do other things on the container that we need to craft the environment
- start the container
- collect the output from the command execution
- validate using the following:
- check status code
- validate output of the command
- `docker diff test` to …

integration-test: add test scenarios

---

cmds.go
download/retry.go
download/retry_test.go
download/save.go
download/save_test.go
files.go
files_test.go

Plumbing logger reference into the download package so that
users can get more visibility into the download failures
during the retries by looking at the logs.
```log
time=2016-07-26T22:28:51Z version=v2.0.0-beta/git@c5044e0-dirty operation=enable seq=0 files=1
time=2016-07-26T22:28:51Z version=v2.0.0-beta/git@c5044e0-dirty operation=enable seq=0 file=0 event="download start"
time=2016-07-26T22:28:52Z version=v2.0.0-beta/git@c5044e0-dirty operation=enable seq=0 file=0 retry=0 error="unexpected status code: got=404 expected=200"
time=2016-07-26T22:28:52Z version=v2.0.0-beta/git@c5044e0-dirty operation=enable seq=0 file=0 retry=0 sleep=3s
time=2016-07-26T22:28:55Z version=v2.0.0-beta/git@c5044e0-dirty operation=enable seq=0 file=0 retry=1 error="unexpected status code: got=404 expected=200" …
```

download: plumb logger for logging retries

---

download/blob_test.go
integration-test/test/basic.bats
integration-test/test/handler-commands.bats

When AZURE_STORAGE_ACCOUNT and AZURE_STORAGE_ACCESS_KEY passed,
we now have a scenario that runs by uploading two 512k files to
Azure Blob Storage and configures extension to download it.
We verify by checking test container fs diff to see files are
downloaded and we verify checksum on one of the files.

integration-test: add storage tests for blobs as fileUris

---

misc/custom-script-shim

Wrote a bash shim that forwards logs of the handler process
reliably and daemonizes the 'enable' command via `nohup .. &`.
Adopted from https://github.com/Azure/azure-docker-extension/blob/master/scripts/run-in-background.sh and extended to be used for all commands (not just 'enable')
Fixes #35.
------
`custom-script-extension install` (attached to the process tree):
```
bash,1
`-fake-waagent,79 /sbin/fake-waagent install
`-custom-script-s,88 ./Extension/bin/custom-script-shim install
|-custom-script-e,94 /var/lib/waagent/Extension/bin/custom-script-extension install
`-custom-script-s,91 ./Extension/bin/custom-script-shim install
`-tee,93 -ia /var/log/azure/custom-script/handler.log
```
`custom-script-extension enable` (detached from the process tree):
```
bash,1
|-custom-script-e,157 …
```

Shim script for extension handler

---

integration-test/env/wait-for-enable
integration-test/test/handler-commands.bats
test.Dockerfile

Since #39 is adding a shim that daemonizes 'enable' command and
exits and shim is the entrypoint of the container command, Docker
will kill the container when that entrypoint exits (will not wait
background process to finish). This adds a `wait-for-enable` command
that we use in integration tests. It runs inside the test container
and loops indefinitely until the background process exits.
Also by detaching enable cmd from the process tree, we lose ability
to get its exitcode, but we will still keep validating its output so we're good.
Should be merged once #39 is in.

integration-test: fix for daemonized 'enable' cmd

---

.travis.yml
Makefile

:warning::warning: this is expected  to fail until #24 and #32 are merged. once they are in, I will rebase and we should start getting CI running our integration test suite as well.
-----
- change sudo:true so that we can get a Docker engine
- this will slow down the time to get a test box (a few mins)
but it should be fine
- add bats in 'install'
- print docker info prior to testing
- execute bats

travis.yml: add integration tests

---

integration-test/env/wait-for-enable

Inside the container when we invoke `nohup [...] &` it immediately
returns and `wait-for-enable` starts checking `ps aux` for extension
binary. However since travis environment is not fast, `wait-for-enable`
exited immediately once before the process started.
Adding a 1s delay while polling for exit of extension process should
solve this problem.
cc: @boumenot

wait-for-enable: add initial 1s delay

---

Makefile
manifest.xml

Extension deployment pipeline requirements.
- Added a manifest.xml (which has a version number that should be
kept in sync with `./VERSION` file)
- Added a `make bundle` command which should produce a `bundle/custom-script-extension.zip`
cc: @boumenot

EDP: add `make bundle` and manifest.xml

---

integration-test/test/handler-commands.bats
integration-test/testdata/script.sh

Checking in the external test file. The CI is supposed to fail and succeed back again once merged.
This is less dependent on github gist and more on github's URL redirection for raw files and the source tree structure now.

integration-test: remove dependency to gist

---

main/cmds.go
main/cmds_test.go
main/main.go
main/status.go
main/status_test.go

Apparently waagent-2.0.x included a `SeqNo` field in HandlerEnvironment.xml
and 2.1.x removed it (it was not covered by the extensions spec). Other
extensions were using `vmextension.FindSeqNum(...)` method to locate the
highest sequence number.
Switching this handler to use it as well and refactoring a few methods
accordingly.
cc: @boumenot

Do not rely on SeqNo in HandlerEnvironment.xml

---

integration-test/test/handler-commands.bats
main/cmds.go
main/main.go
main/migration.go
main/migration_test.go
misc/manifest.xml

Adding code to migrate /var/lib/azure/custom-script to
/var/lib/waagent/custom-script so that it gets cleaned up on
'waagent -deprovision' path. Shelling out to `mv -f` for recursive
file copying.
Also bumped version to v2.0.1.
cc: @boumenot

cmd/enable: migrate old data dir on enable

---

integration-test/test/handler-commands.bats
main/cmds.go
main/main.go
misc/custom-script-shim

Updating custom-script-shim to not to overwrite a placeholder
"transitioning" `.status` file if it already exists.
Updating handler code writing "transitioning" `.status` file to
not to write the `.status` file until the sequence number check
is completed in the "enable" cmd.
Added integration tests to validate this case.
cc: @boumenot

Do not overwrite .status file in new enables

---

.travis.yml
pkg/download/blob_test.go

The storage tests started to get "no such error" instead of HTTP 403
because the owner of 'accountname' account deleted the account. So
changing it to 'example' for the time being.
Also disabling CLI telemetry prompt, saves 30s in tests.

fix tests with new storage account name

---

.travis.yml
integration-test/test/handler-commands.bats
main/cmds.go
main/exec.go
main/exec_test.go
main/logtail.go
main/logtail_test.go
main/main.go

See #67 for more info.
This change adds executed tail (max: 4k) of the executed script's stderr/stdout into the status message delivered via `.status` file. A new status file is in the format of:
Enable (succeeded|failed): \n[stdout]\n(..bytes..)\n[stderr]\n(..bytes..)
And it looks like this in practice where `"commandToExecute": "echo HelloStdout>&1; echo HelloStderr>&2"`:
```json
[
{
"version": 1,
"timestampUTC": "2016-11-28T23:41:31Z",
"status": {
"operation": "Enable",
"status": "success",
"formattedMessage": {
"lang": "en",
"message": "Enable succeeded: \n[stdout]\nHelloStdout\n\n[stderr]\nHelloStderr\n"
}
}
}
]
```
cc: @boumenot

Tail stdout/stderr files in enable status message

---

misc/HandlerManifest.json

The extension should be executing install upon upgrade.  The uninstall operation deletes the scratch directory, and install must run to re-create that directory.
Closes #114

Auto create dataDir on preEnable

---

misc/custom-script-shim

So that custom-script-shim works on distros where bash is not in /bin

Find bash from env

---

.travis.yml
Makefile
README.md
main/cmds.go
main/files.go
main/files_test.go
main/handlersettings.go
main/handlersettings_test.go
main/schema.go
main/schema_test.go
misc/manifest.xml
pkg/download/blob_test.go
pkg/download/blobwithmsitoken.go
pkg/download/blobwithmsitoken_test.go
pkg/download/downloader.go
pkg/download/downloader_test.go
pkg/download/retry.go
pkg/download/retry_test.go
pkg/download/save.go
pkg/download/save_test.go

Enable CSE linux to use managed identities to access azure storage blobs to download scripts.

RBAC support for downloading scripts with managed identities

---

misc/custom-script-shim
misc/manifest.xml

Fix for text file busy custom-script-extension binary.
Use the shim file to detect open file handles to custom-script-extension binary, and kill the processes that own them before attempting to execute the binary.

Fix for text file busy error for custom-script-extension binary

---

misc/custom-script-shim
misc/manifest.xml
pkg/download/blobwithmsitoken.go

Updated wait behavior for open file handles to custom-script-extension binary
Also removed call stack from the error message which is generated when user specifies a non existent managed identity.

Updated wait behavior for open file handles to custom-script-extension binary

---

go.mod
go.sum
main/files.go
pkg/download/blob.go
pkg/download/blob_test.go
pkg/download/blobwithmsitoken.go
pkg/download/blobwithmsitoken_test.go
pkg/download/downloader.go
pkg/download/downloader_test.go
pkg/download/retry.go
pkg/download/retry_test.go
pkg/download/url.go

For [Error Improvements in VM Extensions](https://microsoft.sharepoint.com/:w:/t/ComputeVM/ERQYqh3QTktFrdtAgBMZvAgBLKT8DqKH3K0rKznDVCr11A?e=bJE1Zm) , when downloading scripts we will log the request ID, response ID, and response code (if provided) and give specific error messages for status codes 401, 404, 400, 500.

Track Request ID, Response ID, and Response Code + Add response-code-specific error messages

---

pkg/download/retry.go
pkg/download/retry_test.go
pkg/download/save.go

What operation are we performing on behalf of the customer?
- Downloading the script files and saving them to locla disk
What part of this operation are we retrying on?
- Just the HTTP download and that too only if status is not 200 
What should we be retrying ideally?
- The entire operation  = HTTP request + streaming response + writing streamed bytes to local disk
This PR aims to make all parts of the operation retryable.

Include the entire read response body and file save operation inside retry method

---

main/cmds.go

By removing this logic: 
- Upgrades that do not have mrseq file present will cause the currentSeqNum to run. 
- Upgrades that do have mrseq file present will honor the number in the mrseq file and only execute if mrseqNum less than the currentSeqNum.
- If it is the first ever install, the script will also run since there is no mrseq file to compare currentSeqNum to.

Removing migrate to mostRecentSeqNum logic

---

main/handlersettingscommon.go

Openssl cms command is needed to support FIPS 140-3, keeping smime command as a backup 
Doc: [Support for FIPS 140-3 in VM Agents and Extensions](https://microsoft.sharepoint.com/:w:/t/ComputeVM/EQuno8Nmz3ZHkiWuFxXT_D8BjevZAW4YbX0f1ArT10wIjQ?e=U2hpMD&nav=eyJoIjoiMTAxMDA5MjcwMiJ9)

Adding support for FIPS 140-3
